# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Barrierefreie Kommunikation der Landesregierung Berlin
author: |
  <a ref="https://quadriga-dk.de">QUADRIGA</a>
logo: book_images/quadriga-logo.jpeg
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


# reference style
sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Information about where the book exists on the web
repository:
  url: https://github.com/dh-network/quadriga-fs-2
  branch: develop

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: jupyterlab
  colab_url: "https://colab.research.google.com"
  # binderhub_url: "https://mybinder.org"
  # thebe: true

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

# Files to exclude from the build
#exclude_patterns: [] 

# Enable interactive widgets
jupyter:
widgets:
  enable: true
